Error in running func1! (Logged to error.log)
