try:
    print(n)
except Exception as e:
    print(e)  # name 'n' is not defined